name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --upgrade pip setuptools wheel hatchling
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        run: pytest

      - name: Secret Scan (Git Diff)
        run: ./run.sh --git-branch origin/main --format sarif > secret-results.sarif
        continue-on-error: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: secret-results.sarif
        if: hashFiles('secret-results.sarif') != ''

      - name: Lint regex
        run: python tools/regex_lint.py

#      - name: Safe regex
#        run: python tools/run_safe_regex.py

#      - name: ReDoS protection
#        run: python tools/run_redoctor.py
